{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggdensity
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggdensity_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggdensity/ggdensity_{{ version }}.tar.gz
  sha256: 1b39707320dc528f2366c69f3e71f85998a6a93e7dbdab0cddb5a6ef87d83c03

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-ggplot2
    - r-isoband
    - r-scales
  run:
    - r-base
    - r-mass
    - r-ggplot2
    - r-isoband
    - r-scales

test:
  commands:
    - $R -e "library('ggdensity')"           # [not win]
    - "\"%R%\" -e \"library('ggdensity')\""  # [win]

about:
  home: https://jamesotto852.github.io/ggdensity/
  license: MIT
  summary: The 'ggplot2' package provides simple functions for visualizing contours of 2-d kernel density estimates. 'ggdensity' implements several additional density estimators as well as more interpretable visualizations based on highest density regions instead of the traditional height of the estimated density surface.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
